name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: 'maven'

    - name: Compile the code
      run: mvn compile

    - name: Run unit tests
      run: mvn test

    - name: Create installers
      run: mvn package

  acceptance:
    runs-on: ubuntu-latest
    needs: commit

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: 'maven'

    - name: Run smoke tests
      run: mvn test -Dtest=*SmokeTest

    - name: Run acceptance tests
      run: mvn test -Dtest=*AcceptanceTest

  capacity:
    runs-on: ubuntu-latest
    needs: acceptance

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: 'maven'

    - name: Run capacity tests (optional)
      run: mvn test -Dtest=*CapacityTest
