name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compile the code
      run: mvn compile
      working-directory: ./gerencia

    - name: Run unit tests
      run: mvn test
      working-directory: ./gerencia

    - name: Package the application
      run: mvn package
      working-directory: ./gerencia

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./gerencia/target/surefire-reports/
