name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Compile the code
      run: mvn compile
      working-directory: ./gerencia

    - name: Run unit tests
      run: mvn test -Dtest=PacienteTest -DfailIfNoTests=false
      working-directory: ./gerencia

    - name: Run integration tests
      run: mvn test -Dtest=PacienteRepositoryTest -DfailIfNoTests=false
      working-directory: ./gerencia

    - name: Run smoke tests
      run: mvn test -Dtest=SmokeTest -DfailIfNoTests=false
      working-directory: ./gerencia

    - name: Run acceptance tests
      run: mvn test -Dtest=AcceptanceTest -DfailIfNoTests=false
      working-directory: ./gerencia

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./gerencia/target/surefire-reports/

  acceptance:
    runs-on: ubuntu-latest
    needs: commit

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run smoke tests
      run: mvn test -Dtest=SmokeTest -DfailIfNoTests=false
      working-directory: ./gerencia

    - name: Run acceptance tests
      run: mvn test -Dtest=AcceptanceTest -DfailIfNoTests=false
      working-directory: ./gerencia

  capacity:
    runs-on: ubuntu-latest
    needs: acceptance

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run capacity tests
      run: mvn test -Dtest=CapacityTest -DfailIfNoTests=false
      working-directory: ./gerencia
